(window.HTMLStudio=window.HTMLStudio||{}).ContextMenu=function ContextMenu(a){this.getItem=function(b){for(var a=this.node.children,c=a.length-1;0<=c;c--)if(a[c].id==this.id+"-item-"+(b||0))return a[c]};this.node=document.createElement("ul");this.node.root=this.node;this.id=this.node.id="context-"+(new Date).getTime().toString(36);this.node.className="contextmenu";this.node.style.listStyle="none";this.node.style.display="inline-block";this.node.style.position="absolute";this.node.style.left=this.node.style.top=
"0";this.node.style.zIndex=9999996;for(var c=a.items.length-1;0<=c;c--)(function(){var b=document.createElement("li"),d=document.createElement("div"),f=document.createElement("span"),g=document.createElement("div"),l="pad"in a.items[c]&&!a.items[c].pad,e=a.items[c];b.className="contextmenuitem";b.id=this.id+"-item-"+c;b.root=this.node;for(prop in a.items[c].attributes||{})b[prop]=a.items[c].attributes[prop];var h=a.items[c].disabled,m=a.items[c].toggled||!1;if(Object.defineProperties(b,{disabled:{get:function(){return h},
set:function(a){h=!!a;(b.children[1]||b.firstChild).style.color=a?"#AAA":"";b.title=e[a&&e.disabledtitle?"disabledtitle":"title"];a&&e.disabledimage&&b.children[0].className.includes("contextmenuitemimage")?b.children[0].style.backgroundImage='url("'+e.disabledimage+'")':e.image&&b.children[0].className.includes("contextmenuitemimage")&&(b.children[0].style.backgroundImage='url("'+e.image+'")')},enumerable:!0,configurable:!0},toggled:{get:function(){return m},set:function(a){m=!!a;e.toggle&&!l&&(b.firstChild.style.backgroundImage=
'url("'+(a?e.image||"":e.imageoff||e.image||"")+'")')}}}),b.func=a.items[c].func,l?b.style.width="calc(12rem + 1.7em)":(a.items[c].toggle?d.style.backgroundImage=a.items[c].toggled?'url("'+a.items[c].image||'")':'url("'+(a.items[c].imageoff||a.items[c].image||"")+'")':!a.items[c].image||a.items[c].disabled&&a.items[c].disabledimage?a.items[c].disabledimage&&a.items[c].disabled&&(d.style.backgroundImage='url("'+a.items[c].disabledimage+'")'):d.style.backgroundImage='url("'+a.items[c].image+'")',d.className=
"contextmenuitemimage",d.style.width="1.4em",d.style.height="1.4em",d.style.backgroundSize="100% 100%",d.style.display="inline-block",d.style.position="absolute",d.style.left=".3em",d.style.top="0em",d.style.pointerEvents="none",d.root=this.node,b.style.paddingLeft="2.1em",b.appendChild(d)),g.style.width="auto",g.style.textOverflow="ellipsis",g.style.overflowX="hidden",g.style.pointerEvents="none",g.root=this.node,g.className="contextmenuitemtextcontainer",h&&(g.style.color="#AAA"),b.appendChild(g),
f.className="contextmenuitemtext",f.innerHTML=a.items[c].name||" ",f.style.pointerEvents="none",f.style.MozUserSelect="-moz-none",f.style.WebkitUserSelect="none",f.style.MsUserSelect="none",f.style.userSelect="none",f.root=this.node,g.appendChild(f),!a.items[c].title||h&&a.items[c].disabledtitle?a.items[c].disabledtitle&&h&&(b.title=a.items[c].disabledtitle):b.title=a.items[c].title,a.items[c].func&&b.addEventListener("click",function(a){h||b.func.call(this,a,function(){b.style.background="#F5F5F5";
b.root.parentNode&&b.root.parentNode.removeChild(b.root)})}),b.addEventListener("mouseenter",function(){if(this.style.backgroundColor=h?"#E5E5E5":"#B2EBF2",this.style.whiteSpace="pre-line",this.style.height="",e.subcontext){var a=new HTMLStudio.ContextMenu(e.subcontext),c=b.getBoundingClientRect();a.node.parent=b;a.node.className+=" subcontextmenu";a.node.style.top=em(-.2)-1+"px";a.node.style.left=c.width+"px";a.node.style.position="absolute";this.appendChild(a.node)}}),b.addEventListener("mouseleave",
function(a){if(this.style.backgroundColor="",this.style.whiteSpace="nowrap",this.style.height="1.4em",e.subcontext)for(a=this.children.length-1;0<=a;a--)this.children[a].className.includes("subcontextmenu")&&this.removeChild(this.children[a])}),b.addEventListener("mousedown",function(){this.style.backgroundColor=h?"#E5E5E5":"#A0D3D9"}),b.addEventListener("mouseup",function(){this.style.backgroundColor=h?"#E5E5E5":"#B2EBF2"}),b.style.padding=b.style.paddingLeft?".05em .4em .05em 2.1em":".05em .4em",
b.style.paddingTop=".075em",b.style.paddingBottom=".025em",b.style.paddingRight=".4em",b.style.paddingLeft=b.style.paddingLeft||".4em",b.style.width=b.style.width||"12rem",b.style.height=b.style.minHeight="1.4em",b.style.textOverflow="ellipsis",b.style.whiteSpace="nowrap",b.style.position="relative",a.items[c].separate)b.style.marginBottom="calc(.2em + 1px)",d=document.createElement("div"),d.className="contextmenuitemseparator",d.style.width="calc(12rem + 1.7em)",d.style.height="1px",d.style.backgroundColor=
"#C5C5C5",d.style.position="relative",d.style.top="-.15em",d.style.left=".4em",this.node.insertBefore(d,this.node.firstChild);if(a.css)for(var k in a.css)b.style[k]=a.css[k];if(a.items[c].css)for(k in a.items[c].css)b.style[k]=a.items[c].css[k];this.node.insertBefore(b,this.node.firstChild)}).call(this)};